### ISSUE TITLE
Mobile Message - Incomplete RTMI 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-DEVELOPMENT#178]
As Discussed via phone, what could cause this message to show up ?
![image](https://cloud.githubusercontent.com/assets/5666297/7800175/35aba6e6-02df-11e5-83bb-6fa41f502aac.png)

**Comment by gchan-trailcon** [comment]
How do we test it if we don't know how to duplicate the error?

**Comment by giovanicani** [comment]
issue resolved.
