### ISSUE TITLE
Duplicate RTMI created for the same unit

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#187]
User Vince Gardiner discovered that 2 RTMI (30111 and 30112) were created for the same unit 305299.
He has voided one and continue with the other.

Question: does RTMI allow creating multiple records for the same unit?  Should it be restricted to have only 1 active RTMI per unit?

**Comment by giovanicani** [comment]
this has been fixed.
