### ISSUE TITLE
Reefer Reading Changes

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-DEVELOPMENT#210]
See spec attached for detailed info on the change.

[CR-ReeferReadings-RTMI.pdf](https://github.com/GCSO2/D3STESTING/files/3592/CR-ReeferReadings-RTMI.pdf)

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Done and released.
