### ISSUE TITLE
SCR: RTMI summary does not show the same info of the RTMI detail

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#215]
Issue: SCR# 688, RTMI with unit 605.  The Outbound location is changed to Edmonton.  But the summary screen is still showing "Mississauga Branch".

**Comment by d3sqa** [comment]
The summary grid is now displaying the updated data correctly. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
checked.
