### ISSUE TITLE
SCR: Revenue Location not using the one specified in the SCR

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#216]
Issue: the Revenue Location of the new RTMI created from SCR still uses the one from the old RTMI.
For example, SCR 688, the Revenue Location is Mississauga.  But the new RTMI created from this SCR all shows the same Revenue Locations from the old RTMI (Calgary, Cornwall).

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The Revenue location for new RTMI reflects the same location given in the SCR and not the one from old RTMI. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
verified
