### ISSUE TITLE
SCR: Change the button label from "Create SCR" to "Create RTMI"

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#219]
Change the button label from "Create SCR" to "Create RTMI"

Please see the screenshot for which button to change

![capture](https://cloud.githubusercontent.com/assets/6808323/11830737/c8bf2228-a375-11e5-9358-61c529e96f07.JPG)

**Comment by d3sqa** [comment]
The Create SCR button has been renamed to Create RTMI button. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
checked.
