### ISSUE TITLE
SCR: Order RTMI by unit number in ascending order

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#221]
Currently the RTMI are ordered in descending order.
Would you please order them in ascending order?

![capture](https://cloud.githubusercontent.com/assets/6808323/11880347/3a80c5ac-a4ce-11e5-9c5c-9692c8180f5d.JPG)

**Comment by d3sqa** [comment]
The sort has been changed to Ascending order for unit numbers. Ready to test in UAT Environment

![image](https://cloud.githubusercontent.com/assets/13255706/11891808/ce1b0c5e-a583-11e5-946d-485adac0add3.png)

**Comment by gchan-trailcon** [comment]
checked.
