### ISSUE TITLE
SCR: Add RTMI type into SCR header and RTMI detail

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#222]
Please add the "Type" field (drop down list) to the SCR header (as default for all RTMI under this SCR).  And add this field to each RTMI detail so that user can override the default individually.

The values of the Type
- SAME
This is the default value.  When this is selected, the new RTMI will be created with the same type as the old RTMI.
- RENTAL
When this is selected, the new RTMI will be created with type RENTAL, regardless what the old RTMI type is.
- LEASE
When this is selected, the new RTMI will be created with type LEASE, regardless what the old RTMI type is.

**Comment by d3ssupport** [comment]
Changes Done. Ready for testing in UAT

**Comment by gchan-trailcon** [comment]
Verified.
