### ISSUE TITLE
Unit # and barcode for testing in production

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#224]
TC unit
350442 – T002036

Non-TC unit
9H0242 (owned by Walmart 785) – C007798

**Comment by gchan-trailcon** [comment]
For the SCR test: SCR# SCRTEST001, the old RTMI00031811 and the new RTMI031812 are not in EMDECS.  Would you please check?
And I don't think future dates in RTMI start and termination will work in EMDECS.

**Comment by gchan-trailcon** [comment]
Here is what (rental/lease agreements) EMDECS has for unit 350442.

![capture](https://cloud.githubusercontent.com/assets/6808323/12020282/a17efe40-ad48-11e5-8a5c-5526009e9899.JPG)

**Comment by gchan-trailcon** [comment]
Would you please check the data export to EMDECS in SCR?  If the RTMI APPROVAL was sent to EMDECS, it should have returned an error.  But in the SCR test, the RTMI status does not reflect that.

Thanks

**Comment by gchan-trailcon** [comment]
I am going to void both the old and new RTMI for that unit and re-test.

**Comment by gchan-trailcon** [comment]
When I try to complete the outbound inspection for RTMI00031813, I get this error message.  Would you please check ASAP?

![capture_01](https://cloud.githubusercontent.com/assets/6808323/12020856/ab496b3a-ad4e-11e5-890a-0011d3f1651f.JPG)

**Comment by gchan-trailcon** [comment]
The error is resolved by updating the mobile app.

**Comment by gchan-trailcon** [comment]
New issue:
copied and pasted from Skype chat:
"Please check RTMI 31813 and 31814.  31813 was created from normal RTMI and outbound inspected approved to EMDECS.  Then I tried the SCR (TEST #2), it creates RTMI 31814.  But non of the RTMI information is sent to EMDECS."

**Comment by d3ssupport** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Please check this RTMI in EMDECS. 

![1 image](https://cloud.githubusercontent.com/assets/13255706/12031148/6f5cdbf2-ae2a-11e5-8a1f-1d178ba15a4b.png)

**Comment by gchan-trailcon** [comment]
Yes, the data appears in EMDECS.  Thanks.  I will do more checking before closing the issue.

**Comment by gchan-trailcon** [comment]
verified
