### ISSUE TITLE
SCR: photos not copied from old RTMI to new RTMI

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#225]
Photos not copied from old RTMI to new RTMI
Example: SCR# TESTSCR02

None of the "overview" photos and none of the damage/fail photos are copied from old RTMI to new RTMI.

**Comment by d3ssupport** [comment]
Work in progress

**Comment by d3ssupport** [comment]
The RTMI was processed on OLD debug which contain some missing information regarding to SCR. i put a check for OLD Debug RTMI's. Now images are reflecting at RTMI00031814.

**Comment by gchan-trailcon** [comment]
the new RTMI now has all the images.
Closing issue
