### ISSUE TITLE
SCR: RTMI not going to EMDECS

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#227]
Hi D3S,
We have started using real data in SCR# 632A
Both RTMI have been "OK".  But they do not go to EMDECS.  Would you please check ASAP?

Thanks

**Comment by gchan-trailcon** [comment]
We would really like to have this fixed ASAP.  Please keep me updated on the progress.  Thank you.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
We have resent the RTMIs (RTMI00031836 and RTMI00031835) to EMDECS. Please validate in EMDECS now

**Comment by gchan-trailcon** [comment]
working now.
