### ISSUE TITLE
SCR: Copy Signatures from old RTMI to new RTMI

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#228]
The signatures and other data in the RTMI "Signatures" tab should also be copied from the old RTMI to the new RTMI.

For example: the 2 RTMI in SCR# 632A

Thanks

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Signatures are now successfully copied from old RTMI to new RTMI. This fix has been available at Production environment.

Please see below screenshots:

Old RTMI RTMI00017234

![image](https://cloud.githubusercontent.com/assets/13255706/12112753/65787114-b3c0-11e5-9ba4-09138ea5390e.png)

New RTMI RTMI00031835

![image](https://cloud.githubusercontent.com/assets/13255706/12112759/70ede5ec-b3c0-11e5-8eb9-58a0393e0f4a.png)

**Comment by gchan-trailcon** [comment]
Verified
