### ISSUE TITLE
SCR: new readings should not change old RTMI Outbound data

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#229]
As discussed with Tufail and Gene on Jan 6th Skype call - the odometer and reefer readings in the SCR should not change the Outbound data of the Old RTMI.
Since the Old RTMI has been Outbound Approved, the outbound data should not be changed at all.

The SCR Safety certificate data SHOULD be changed in both the old and new RTMI because safety data is not considered as outbound or inbound.

**Comment by gchan-trailcon** [comment]
D3S team is currently fixing the outbound odometer reading data of the old RTMI.
Gary has provided the original data to D3S.

**Comment by d3sqa** [comment]
Data fixing has been done at production environment

**Comment by gchan-trailcon** [comment]
verified.
