### ISSUE TITLE
SCR: Safety data should update both old and new RTMI

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#231]
In a SCR, if user enter safety data, it should update both the old RTMI and the new RTMI.

**Comment by tufailzafar** [comment]
work in progress

**Comment by gchan-trailcon** [comment]
Any update?

**Comment by d3sqa** [comment]
Done at UAT environment. Please see screenshot below:

![34343434343434](https://cloud.githubusercontent.com/assets/13255706/12529544/ba88858e-c1dc-11e5-947d-23bd6cb2d447.png)

**Comment by d3sqa** [comment]
This fix has been propagated to the production as well

**Comment by gchan-trailcon** [comment]
Checked.  Thanks. Closing
