### ISSUE TITLE
SCR: Make the safety information mandatory for each unit

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#232]
In SCR, for the unit detail window, make the safety information (certificate letter, safety number, date) mandatory for each unit.  
If these data are not entered, the "OK" button won't perform the task.  It will display error message like "Please enter safety data for the unit".

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Safety certificate fields are now mandatory. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
Passed test. Please apply to next update.
