### ISSUE TITLE
SCR: clicking the "New RTMI#" should open a new browser tab, like clicking "RTMI#"

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#234]
In a SCR, when clicking a RTMI number in the "New RTMI #" column, it should open a new browser tab, just like when clicking a RTMI in the "RTMI #" column.
![scr issue rtmi](https://cloud.githubusercontent.com/assets/6808323/14388494/6c82772e-fd7c-11e5-86d2-719971294b72.jpg)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
By clicking the New RTMI #, the RTMI will be opened in a new browser tab. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
Passed test.  Thanks.  Please apply to next update.
